 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  av_caption: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:


        test:
          # url: /mnt/bn/vlpopt/minigpt4_anno/msrvtt/annotations/cap_test.json
          url: /mnt/bn/sihanchen/datasets/valor1m/desc_test_asr.json
          # storage: msrvtt/annotations/cap_test.json
          storage: valor/annotations/desc_test_asr.json
      videos:
        storage: /mnt/bn/vlpopt/dataset/audioset/frames_recons
      audios:
        storage: /mnt/bn/vlpopt/dataset/audioset/audio_22050hz_recons
